### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by SduyXD** [mpeterson2/save-session#53] opened 2015-01-23 22:46 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.addListeners (/Users/sduy/.atom/packages/save-session/lib/project.coffee:34:9)
```

**Comment by mpeterson2** [comment] 2015-01-24 08:41
I'm aware of this. Just haven't had time to work on it yet. This is a duplicate of #49, so I'm going to close it.

**Closed by mpeterson2** 2015-01-24 08:41 UTC
Labels: duplicate
