### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by zqjimlove** [mpeterson2/save-session#108] opened 2015-04-14 11:06 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Unknown Windows Version
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package, v0.13.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At C:\Users\Dio\.atom\packages\save-session\lib\files.coffee:22

TypeError: Cannot read property 'getPath' of undefined
  at Object.module.exports.save (C:\Users\Dio\.atom\packages\save-session\lib\files.coffee:22:54)
  at C:\Users\Dio\.atom\packages\save-session\lib\files.coffee:81:24

```

### Commands

```
     -3:20.5 markdown-preview:toggle (atom-text-editor.editor)
 14x -3:15.1 core:backspace (atom-text-editor.editor)
     -3:01.4 core:select-all (atom-text-editor.editor)
     -3:00.6 core:backspace (atom-text-editor.editor)
     -2:56.7 editor:consolidate-selections (atom-text-editor.editor)
     -2:56.7 core:cancel (atom-text-editor.editor)
     -2:56.0 grammar-selector:show (atom-text-editor.editor)
 17x -2:55.0 core:move-down (atom-text-editor.editor.mini)
     -2:48.3 core:confirm (atom-text-editor.editor.mini)
     -2:44.9 snippets:next-tab-stop (atom-text-editor.editor)
     -2:44.9 snippets:expand (atom-text-editor.editor)
     -2:10.2 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -1:38.9 window:focus-pane-above (ul.list-inline.tab-bar.inset-panel)
  3x -1:26.4 pane:close (ul.list-inline.tab-bar.inset-panel)
     -0:12.3 core:select-all (atom-text-editor.editor)
     -0:11.5 core:backspace (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false
  },
  "save-session": {
    "dataSaveFolder": "C:\\Users\\Dio\\.atom\\packages\\save-session\\projects",
    "projects": []
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.24.0
autocomplete-plus, v2.7.1
emmet, v2.3.7
highlight-line, v0.10.1
javascript-snippets, v1.0.0
jshint, v1.3.1
linter-csslint, v0.0.11
project-manager, v1.15.5
save-session, v0.13.1

# Dev
No dev packages
```

**Comment by johnkeates** [comment] 2015-04-20 23:54
Got it too, just now. On OS X. Closing a window/tab with a file that no longer exists.

**Comment by icedream** [comment] 2015-05-02 04:10
Same on Windows 8.1 but when opening a CSS file, editing and saving it.

**Comment by chalasr** [comment] 2015-05-13 09:34
Same problem on Ubuntu 14.04 LTS. One error per file reopened , in console.

**Comment by mpeterson2** [comment] 2015-05-16 03:37
Closing old issues that are probably irrelevant to the code just to clear up the clutter. Go ahead and open a new issue if there is still a problem.

**Comment by niedzielski** [comment] 2015-05-17 00:45
This just happened to me a few minutes ago. I'm not quite sure on the repro steps but here's my recollection:

1. Run `atom Desktop` from the command line.
1. Open a new tab and type some rubbish in there.
1. Run `killall -9 atom` to test whether save-session works like Sublime Text.
1. Run just `atom` from the command line since I wouldn't know what folder I was in during a bad crash.
1. Observe that nothing is remembered and this error occurs.


**Atom Version**: 0.198.0
**System**: linux 3.19.0-16-generic
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package, v0.15.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /home/stephen/.atom/packages/save-session/lib/files.coffee:22

TypeError: Cannot read property 'getPath' of undefined
    at Object.module.exports.save (/home/stephen/.atom/packages/save-session/lib/files.coffee:35:56)
    at /home/stephen/.atom/packages/save-session/lib/files.coffee:96:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "soda-light-ui",
      "one-light-syntax"
    ],
    "autoHideMenuBar": true
  },
  "save-session": {
    "dataSaveFolder": "/home/stephen/.atom/packages/save-session/projects"
  }
}
```

### Installed Packages

```coffee
# User
hidpi, v0.5.0
jshint, v1.3.5
language-fish-shell, v1.0.2
language-gradle, v0.0.3
language-mediawiki, v0.1.0
linter-jshint, v0.1.2
save-session, v0.15.0
script, v2.19.0
soda-light-ui, v0.2.0

# Dev
No dev packages
```

**Comment by mpeterson2** [comment] 2015-05-17 17:41
I'll take a look at this when I get a chance. Thanks for reporting it.

**Comment by mrz1836** [comment] 2015-05-21 23:16
Same thing - Windows 8.1

Trace:

C:\Users\MrZ\.atom\packages\save-session\lib\files.coffee:22
Hide Stack Trace
TypeError: Cannot read property 'getPath' of undefined
  at Object.module.exports.save (C:\Users\MrZ\.atom\packages\save-session\lib\files.coffee:22:54)
  at C:\Users\MrZ\.atom\packages\save-session\lib\files.coffee:68:24

**Comment by binarybirchtree** [comment] 2015-05-25 14:17
**Can reproduce this error with the following steps:**
Press Ctrl + N to open a new editor.
Press Enter in the new editor.
Press Ctrl + , to open the Settings panel.
Press Ctrl + W to close the Settings panel.
Press Enter in the new editor again.
Press Ctrl + , to open the Settings panel again.

**More generally:**
Press Ctrl + N to open a new editor.
Type anything in the new editor.
Switch to another tab.
Switch back to the new editor and type anything.
Press Ctrl + , to open the Settings panel.

**OS:** Ubuntu 15.04
**Atom version:** 0.201.0
**save-session version:** 0.15.2

The exception `TypeError: Cannot read property 'getPath' of undefined` occurs in
https://github.com/mpeterson2/save-session/blob/v0.15.2/lib/files.coffee#L22
on the call to `atom.workspace.getActiveTextEditor().getPath()`.

As per the Atom documentation for `getActiveTextEditor()`:
https://github.com/atom/atom/blob/v0.201.0/src/workspace.coffee#L530
> Returns an {TextEditor} or `undefined` if the current active item is not an {TextEditor}.

In the reproducible example above, the "current active item" at the time of the exception would seem to be the Settings panel.

**Possible solution:**
Since the line where the exception occurs only assigns the result of `atom.workspace.getActiveTextEditor().getPath()` to a variable `activePath` which does not appear to be subsequently used (in the current version of the code), maybe that line could be removed altogether.

**Comment by mpeterson2** [comment] 2015-05-25 19:06
`0.15.3` should fix @binarybirchtree's reproductions. Let me know if anyone is still having this issue.

**Closed** 2015-05-25 19:06 UTC
Labels: bug
