### ISSUE TITLE
tab close and ask to Save dialog throws TypeError: undefined is not a function

### ISSUE THREAD

**Issue by DLotts** [mpeterson2/save-session#117] opened 2015-05-28 15:50 UTC
This claims to be the same as closed issue #56.

1. open Atom with an old file with some new unsaved text
2. close the file with the little X in the tab
3. answer dialog with: don't save changes.
4. error pops 
5. file does not close, stays in tab with unsaved modifications.

I did it again in a simpler way and reproduced:

1. open a new file, type "sadfasdf", save and name file, type after same line "ddd".
2. click blue x in tab.
3. In dialog, click save.
4. error pops, file stays open and modified. 
5. goto step 2 to reproduce again.

**Atom Version**: 0.202.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package, v0.15.3

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\david.lotts\AppData\Local\atom\app-0.202.0\resources\app.asar\src\pane.js:495

TypeError: undefined is not a function
    at Object.module.exports.Pane.promptToSaveItem [as defaultSavePrompt] (C:\Users\david.lotts\AppData\Local\atom\app-0.202.0\resources\app.asar\src\pane.js:495:23)
    at Pane.promptToSaveItem (C:\Users\david.lotts\.atom\packages\save-session\lib\save-prompt.coffee:23:24)
    at Pane.module.exports.Pane.destroyItem (C:\Users\david.lotts\AppData\Local\atom\app-0.202.0\resources\app.asar\src\pane.js:441:18)
    at HTMLDivElement.<anonymous> (C:\Users\david.lotts\AppData\Local\atom\app-0.202.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:183:22)
    at space-pen-ul.jQuery.event.dispatch (C:\Users\david.lotts\AppData\Local\atom\app-0.202.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-ul.elemData.handle (C:\Users\david.lotts\AppData\Local\atom\app-0.202.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
 25x -6:33.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -6:30.8.0 core:select-right (atom-text-editor.editor.is-focused)
  3x -6:29.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -6:28.2.0 core:select-left (atom-text-editor.editor.is-focused)
     -5:58.3.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:56.7.0 core:undo (ul.list-inline.tab-bar.inset-panel)
     -0:52.3.0 core:redo (atom-text-editor.editor.is-focused)
     -0:51.7.0 core:undo (atom-text-editor.editor.is-focused)
     -0:51.5.0 core:redo (atom-text-editor.editor.is-focused)
     -0:51.2.0 core:undo (atom-text-editor.editor.is-focused)
     -0:50.9.0 core:redo (atom-text-editor.editor.is-focused)
     -0:50.5.0 core:undo (atom-text-editor.editor.is-focused)
     -0:50.2.0 core:redo (atom-text-editor.editor.is-focused)
 17x -0:49 core:move-up (atom-text-editor.editor.is-focused)
 31x -0:47.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:30.7.0 core:delete (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "save-session": {
    "dataSaveFolder": "C:\\Users\\david.lotts\\.atom\\packages\\save-session\\projects"
  }
}
```

### Installed Packages

```coffee
# User
column-select, v0.2.0
save-session, v0.15.3
Sublime-Style-Column-Selection, v1.2.4

# Dev
No dev packages
```

**Comment by mpeterson2** [comment] 2015-05-28 23:57
Didn't mean to completely close this.

I fixed the second set of steps, but I couldn't get it to be reproduced on the first set. Anyway, the code for this has been rewritten and is a lot less hacky. Maybe it's all fixed? Let me know.

**Comment by mpeterson2** [comment] 2015-06-17 09:29
Going to close this since there hasn't been any complaints since the last update.

**Closed by mpeterson2** 2015-06-17 09:29 UTC
Labels: bug
