### ISSUE TITLE
atom.workspaceView is no longer available

### ISSUE THREAD

**Issue by kajgies** [mpeterson2/save-session#57] opened 2015-01-30 15:27 UTC
![Image of error](http://puu.sh/feCVf/7369206598.jpg)

Got this error/warning right after installing the package.

**Comment by mpeterson2** [comment] 2015-02-03 23:04
Thanks for submitting the bug. I'm going to close it since it's a duplicate of #49.

**Closed by mpeterson2** 2015-02-03 23:04 UTC
