### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by gabmontes** [mpeterson2/save-session#85] opened 2015-03-22 01:34 UTC
Just closed an unsaved buffer and after pressing "Don't save", the error was thrown. I also had the same unsaved buffer open in a second Atom window that opened a moment ago.

**Atom Version**: 0.182.0
**System**: linux 3.13.0-46-generic
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package, v0.12.2

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /home/gabriel/.atom/packages/save-session/lib/config.coffee:86

TypeError: Cannot read property 'path' of undefined
  at Object.module.exports.saveFile (/home/gabriel/.atom/packages/save-session/lib/config.coffee:86:65)
  at Object.module.exports.save (/home/gabriel/.atom/packages/save-session/lib/files.coffee:34:19)
  at /home/gabriel/.atom/packages/save-session/lib/files.coffee:81:10
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.destroyed (/usr/share/atom/resources/app/src/text-editor.js:270:27)
  at TextEditor.module.exports.Model.destroy (/usr/share/atom/resources/app/node_modules/theorist/lib/model.js:218:14)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app/src/pane.js:459:18)
  at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:179:22)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -6:08.8 editor:newline (atom-text-editor.editor)
     -6:08.3 core:paste (atom-text-editor.editor)
     -4:51.8 editor:consolidate-selections (atom-text-editor.editor)
     -4:51.8 core:cancel (atom-text-editor.editor)
     -4:50.1 grammar-selector:show (atom-text-editor.editor)
     -4:48.0 core:backspace (atom-text-editor.editor.mini)
     -4:47.3 core:move-down (atom-text-editor.editor.mini)
     -4:47.0 core:confirm (atom-text-editor.editor.mini)
     -4:45.2 command-palette:toggle (a.inline-block)
  4x -4:43.4 core:backspace (atom-text-editor.editor.mini)
     -4:42.4 editor:consolidate-selections (atom-text-editor.editor.mini)
     -4:42.4 core:cancel (atom-text-editor.editor.mini)
     -4:40.6 grammar-selector:show (atom-text-editor.editor)
  7x -4:36.5 core:move-down (atom-text-editor.editor.mini)
     -4:35.2 editor:consolidate-selections (atom-text-editor.editor.mini)
     -4:35.2 core:cancel (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "atom-jshint",
      "jshint"
    ]
  },
  "save-session": {
    "dataSaveFolder": "/home/gabriel/.atom/packages/save-session/projects",
    "project": "/home/gabriel/Documents/repos/console",
    "windowX": 65,
    "windowY": 24,
    "windowWidth": 1301,
    "windowHeight": 744
  }
}
```

### Installed Packages

```coffee
# User
highlight-selected, v0.9.1
linter, v0.12.0
linter-jshint, v0.1.0
save-session, v0.12.2

# Dev
No dev packages
```

**Comment by mpeterson2** [comment] 2015-03-22 17:51
This is a duplicate of #84 and should be fixed now.

**Closed by mpeterson2** 2015-03-22 17:51 UTC
Labels: duplicate
