### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by andyday** [mpeterson2/save-session#66] opened 2015-02-07 22:08 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\Andy\AppData\Local\atom\app-0.177.0\resources\app\src\atom.js:54:11)
Object.addListeners (C:\Users\Andy\.atom\packages\save-session\lib\project.coffee:34:9)
```

**Comment by mpeterson2** [comment] 2015-02-08 04:21
This is a duplicate of #49, and has been fixed. Please update the package.

**Closed by mpeterson2** 2015-02-08 04:21 UTC
Labels: duplicate
