### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by Edenhofer** [mpeterson2/save-session#63] opened 2015-02-05 16:15 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:54:11)
Object.addListeners (/home/edh/.atom/packages/save-session/lib/project.coffee:34:9)
```

**Comment by mpeterson2** [comment] 2015-02-05 22:08
This is a duplicate of #49 which was just fixed in #62.

**Closed by mpeterson2** 2015-02-05 22:08 UTC
